### ISSUE TITLE
Stop a notification

### ISSUE THREAD

**Issue by danielo515** [cg-cnu/vscode-remind-me#6]
Hello,

Your extension is very handy, thanks for it. However, I'm on a situation where it's been annoying: I have added a single remind of 1 minute for test it, and it is appearing every minute. There is no way to stop it appearing, it's like the only option is to dismiss it.
I don't see any way of erasing or cancelling it. Could you please help me ?

Thanks in advance.

**Comment by cg-cnu** [comment]
Hey @danielo515, thanks so much for taking the time to raise the issue. I really appreciate the effort 🙇 I fixed it and now it should work fine. If am not asking for too much would you mind testing it out locally before I push it to the marketplace ? Cheers 😄

**Comment by danielo515** [comment]
Sure! Just provide me with the non-official version and some basic instructions and I'll check it out.

Regards

**Comment by cg-cnu** [comment]
Clone this repo and do an npm install and place it inside...
Windows %USERPROFILE%\.vscode\extensions
Mac ~/.vscode/extensions
Linux ~/.vscode/extensions
based on your platform...
Make sure you remove the extension installed from marketplace before doing this step 🙂

**Comment by danielo515** [comment]
Hello @cg-cnu 
I followed your steps

1.  Uninstall the marketplace version
1.  Clone your repository into Mac ~/.vscode/extensions
1.  Npm install
1.  Reload VSCode

When I try to use your extension I get the following error:

command 'remindMe.remind' not found

Regards

**Comment by danielo515** [comment]
Ok, you forgot to mention the execution of the compile script

**Comment by cg-cnu** [comment]
Hey @danielo515 Sorry for the trouble. Yep, forgot to mention the compile script. 
Run this after install `npm run compile` and restart vscode instance. Thanks 👍

**Comment by danielo515** [comment]
I did it already. The extension works fine ! Many thanks

**Comment by cg-cnu** [comment]
Once again thanks so much for bringing the issue to my notice and testing it out. I will release the extension with the update 😄
